### ISSUE TITLE
profile image not loaded

### ISSUE THREAD

**Issue by sungnyun** [osilab-kaist/osi.kaist.ac.kr#5]
changed the profile image, still not updated

**Comment by sungnyun** [comment]
fyi, 
![Uploading profile3.png…]()

**Comment by sungnyun** [comment]
![Uploading profile.jpg…]()

fyi,

**Comment by sungnyun** [comment]
![profile](https://github.com/osilab-kaist/osi.kaist.ac.kr/assets/46050900/17c3a497-912e-4766-acc3-8c24ae25e3b5)
fyi,

**Comment by sungnyun** [comment]
fyi,

![profile](https://github.com/osilab-kaist/osi.kaist.ac.kr/assets/46050900/192a5e44-557c-48a6-9048-5590595467aa)

**Comment by itsnamgyu** [comment]
Fixed it :)

**Comment by sungnyun** [comment]
thanks buddy
