### ISSUE TITLE
Different policy on the publication panel regarding to alumni

### ISSUE THREAD

**Issue by MingyuKim87** [osilab-kaist/osi.kaist.ac.kr#6]
It seems different policy on alumni in the website. Please refer to the pictures as below.

- This is a collaborative work with alumni, Jaehoon and Sangmook
<img width="713" alt="image" src="https://github.com/osilab-kaist/osi.kaist.ac.kr/assets/21028510/76fa81a3-2542-4add-9c83-c7283309f109">

- This is a paper presented this year. Jung-hun was also our lab-member
<img width="785" alt="image" src="https://github.com/osilab-kaist/osi.kaist.ac.kr/assets/21028510/9d9e769a-1543-43b9-9b51-78324a7e27b4">

**Comment by itsnamgyu** [comment]
The underline is based on the name saved on our website. I think Jung-hun was not identified because of `-`. I'll add an exception for Jung-hun and work on a better solution in the future.
